package com.iti.spring.generic.model.entity;
// Generated May 1, 2019 3:16:44 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name="category"
        ,catalog="biddingschema"
)
public class Category  implements java.io.Serializable {


    private Integer id;
    private String value;
    private String description;
    private Set<Product> products = new HashSet<Product>(0);

    public Category() {
    }


    public Category(String value) {
        this.value = value;
    }
    public Category(String value, String description, Set<Product> products) {
        this.value = value;
        this.description = description;
        this.products = products;
    }

    @Id @GeneratedValue(strategy= GenerationType.IDENTITY)


    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }


    @Column(name="value", nullable=false, length=45)
    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }


    @Column(name="description", length=150)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="product_has_category", catalog="biddingschema", joinColumns = {
            @JoinColumn(name="category_id", nullable=false, updatable=false) }, inverseJoinColumns = {
            @JoinColumn(name="product_id", nullable=false, updatable=false) })
    public Set<Product> getProducts() {
        return this.products;
    }

    public void setProducts(Set<Product> products) {
        this.products = products;
    }




}


