package com.iti.spring.generic.model.entity;


// Generated May 1, 2019 3:16:44 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user",catalog="biddingschema")
public class User  implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy=IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    private Integer id;
    @Column(name="email", nullable=false, length=50)
    private String email;
    @Column(name="address", nullable=false, length=150)
    private String address;
    @Column(name="phone", length=45)
    private String phone;
    @Column(name="mobile", length=45)
    private String mobile;
    @Temporal(TemporalType.DATE)
    @Column(name="date_of_birth", length=10)
    private Date dateOfBirth;
    @Temporal(TemporalType.DATE)
    @Column(name="registration_date", nullable=false, length=10)
    private Date registrationDate;
    @Column(name="user_name", nullable=false, length=45)
    private String userName;
    @Column(name="password", nullable=false, length=45)
    private String password;
    @Column(name="full_name", length=100)
    private String fullName;
    @OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    private Set<Buyer> buyers = new HashSet<Buyer>(0);
    @OneToOne(fetch=FetchType.LAZY, mappedBy="user")
    private Seller seller;

    public User() {
    }


    public User(String email, String address, Date registrationDate, String userName, String password) {
        this.email = email;
        this.address = address;
        this.registrationDate = registrationDate;
        this.userName = userName;
        this.password = password;
    }
    public User(String email, String address, String phone, String mobile, Date dateOfBirth, Date registrationDate, String userName, String password, String fullName, Set<Buyer> buyers, Seller seller) {
        this.email = email;
        this.address = address;
        this.phone = phone;
        this.mobile = mobile;
        this.dateOfBirth = dateOfBirth;
        this.registrationDate = registrationDate;
        this.userName = userName;
        this.password = password;
        this.fullName = fullName;
        this.buyers = buyers;
        this.seller = seller;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }


    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }


    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }


    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }


    public String getMobile() {
        return this.mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }


    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }

    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    public Date getRegistrationDate() {
        return this.registrationDate;
    }

    public void setRegistrationDate(Date registrationDate) {
        this.registrationDate = registrationDate;
    }


    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }


    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }


    public String getFullName() {
        return this.fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public Set<Buyer> getBuyers() {
        return this.buyers;
    }

    public void setBuyers(Set<Buyer> buyers) {
        this.buyers = buyers;
    }

    public Seller getSeller() {
        return this.seller;
    }

    public void setSeller(Seller seller) {
        this.seller = seller;
    }




}